name: Create release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.8"
      - name: Install front dependencies
        run: npm ci
      - name: Build front
        run: npm run build:front
      - name: Build backend
        run: npm run build:linux
      - name: Create archive
        run: |
          mkdir outline_web
          mv bin/main.linux.amd64 outline_web/main
          mv templates outline_web/templates
          mv static outline_web/static
          mv Readme.md outline_web/readme.md
          mv LICENCE outline_web/LICENCE
          zip outline_web.zip -r outline_web
        shell: bash
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          files: outline_web.zip
